// ⚠ PLACEHOLDER / DEV-ONLY DATA — superseded by milestone 2.
//
// Typed port of site-specification/Workout-visualizations/workouts-data.jsx.
// These block values are IDEALIZED illustrations (e.g. warmup 0.55→0.75) and do
// NOT match the real .zwo prescriptions. They exist solely to render the
// WorkoutChart gallery at /dev/charts while the component is tuned. Milestone 2
// replaces this with data parsed from the actual .zwo files. Nothing in the
// shipping site imports this file.
import type { ChartBlock, ChartWorkout, Zone } from './chart-model'

export interface ChartExample extends ChartWorkout {
  tier: 'A' | 'T1' | 'T2' | 'T3' | 'T4'
  durMin: number
  tss: number | null
  // Cluster count the handoff says this workout should produce, when known.
  // Used by the gallery to make the clustering sanity checks visible.
  expectedClusters?: number
}

const warmup = (mins = 15): ChartBlock => ({
  kind: 'ramp',
  zone: 2,
  fromPower: 0.55,
  toPower: 0.75,
  dur: mins * 60,
})
const cooldown = (mins = 5): ChartBlock => ({
  kind: 'ramp',
  zone: 1,
  fromPower: 0.6,
  toPower: 0.4,
  dur: mins * 60,
})
const rest = (mins: number, secs = 0): ChartBlock => ({
  kind: 'block',
  zone: 1,
  power: 0.5,
  dur: mins * 60 + secs,
})
const work = (
  zone: Zone,
  power: number,
  mins: number,
  secs = 0,
  cadence = true,
): ChartBlock => ({
  kind: 'block',
  zone,
  power,
  dur: mins * 60 + secs,
  cadence,
})
const sprint = (cadence = true): ChartBlock => ({
  kind: 'block',
  zone: 6,
  power: 1.45,
  dur: 30,
  cadence,
})

const sprintRest: ChartBlock = { kind: 'block', zone: 1, power: 0.45, dur: 30 }

export const CHART_EXAMPLES: ChartExample[] = [
  // ── Adaptation Phase ──────────────────────────────────────────────────────
  {
    id: 'adapt-w1',
    tier: 'A',
    title: 'W1',
    subtitle: '2×10 @ 65–70 rpm',
    durMin: 50,
    tss: null,
    cadenceLabel: '65–70 rpm',
    blocks: [warmup(15), work(2, 0.65, 10), rest(5), work(2, 0.65, 10), cooldown(5)],
  },
  {
    id: 'adapt-w2',
    tier: 'A',
    title: 'W2',
    subtitle: '2×15 @ 65 rpm',
    durMin: 60,
    tss: null,
    cadenceLabel: '65 rpm',
    blocks: [warmup(15), work(2, 0.65, 15), rest(5), work(2, 0.65, 15), cooldown(5)],
  },
  {
    id: 'adapt-w3',
    tier: 'A',
    title: 'W3',
    subtitle: '3×10 @ 60–65 rpm',
    durMin: 65,
    tss: null,
    cadenceLabel: '60–65 rpm',
    blocks: [
      warmup(15),
      work(2, 0.65, 10),
      rest(5),
      work(2, 0.65, 10),
      rest(5),
      work(2, 0.65, 10),
      cooldown(5),
    ],
  },

  // ── Tier 1 ────────────────────────────────────────────────────────────────
  {
    id: 't1-entry',
    tier: 'T1',
    title: 'Entry 4×4',
    subtitle: '4×4 @ 80–85% FTP',
    durMin: 60,
    tss: 38,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 4,
    blocks: [
      warmup(15),
      work(3, 0.82, 4),
      rest(3),
      work(3, 0.82, 4),
      rest(3),
      work(3, 0.82, 4),
      rest(3),
      work(3, 0.82, 4),
      cooldown(15),
    ],
  },
  {
    id: 't1-staple-3x5',
    tier: 'T1',
    title: 'Staple 3×5',
    subtitle: '3×5 @ ~90% FTP',
    durMin: 55,
    tss: 44,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 3,
    blocks: [
      warmup(15),
      work(3, 0.9, 5),
      rest(3),
      work(3, 0.9, 5),
      rest(3),
      work(3, 0.9, 5),
      cooldown(15),
    ],
  },

  // ── Tier 2 ────────────────────────────────────────────────────────────────
  {
    id: 't2-hiit-intro',
    tier: 'T2',
    title: 'HIIT Intro',
    subtitle: '3×3 @ ~110% FTP',
    durMin: 55,
    tss: 50,
    cadenceLabel: '60–70 rpm',
    expectedClusters: 3,
    blocks: [
      warmup(15),
      work(5, 1.1, 3),
      rest(3),
      work(5, 1.1, 3),
      rest(3),
      work(5, 1.1, 3),
      cooldown(15),
    ],
  },
  {
    id: 't2-staple-5x5',
    tier: 'T2',
    title: 'Staple 5×5',
    subtitle: '5×5 @ ~90% FTP',
    durMin: 75,
    tss: 64,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 5,
    blocks: [
      warmup(15),
      work(4, 0.9, 5),
      rest(3),
      work(4, 0.9, 5),
      rest(3),
      work(4, 0.9, 5),
      rest(3),
      work(4, 0.9, 5),
      rest(3),
      work(4, 0.9, 5),
      cooldown(15),
    ],
  },
  {
    id: 't2-staple-5x8',
    tier: 'T2',
    title: 'Staple 5×8',
    subtitle: '5×8 @ ~90% FTP',
    durMin: 90,
    tss: 86,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 5,
    blocks: [
      warmup(15),
      work(4, 0.9, 8),
      rest(3),
      work(4, 0.9, 8),
      rest(3),
      work(4, 0.9, 8),
      rest(3),
      work(4, 0.9, 8),
      rest(3),
      work(4, 0.9, 8),
      cooldown(15),
    ],
  },

  // ── Tier 3 ────────────────────────────────────────────────────────────────
  {
    id: 't3-hiit-4',
    tier: 'T3',
    title: 'HIIT VO2max (4 reps)',
    subtitle: '4×4 @ ~110% FTP',
    durMin: 83,
    tss: 81,
    cadenceLabel: '60–70 rpm',
    expectedClusters: 4,
    blocks: [
      warmup(15),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      cooldown(15),
    ],
  },
  {
    id: 't3-ruegg',
    tier: 'T3',
    title: 'Rüegg VO2max + Sprint',
    subtitle: '3×(5min @ 110% + 1min sprint)',
    durMin: 80,
    tss: 94,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 3,
    blocks: [
      warmup(15),
      work(5, 1.1, 5),
      { kind: 'block', zone: 6, power: 1.3, dur: 60, cadence: false },
      rest(5),
      work(5, 1.1, 5),
      { kind: 'block', zone: 6, power: 1.3, dur: 60, cadence: false },
      rest(5),
      work(5, 1.1, 5),
      { kind: 'block', zone: 6, power: 1.3, dur: 60, cadence: false },
      cooldown(15),
    ],
  },
  {
    id: 't3-thresh-5x5',
    tier: 'T3',
    title: 'Threshold 5×5',
    subtitle: '5×5 @ ~95% FTP',
    durMin: 68,
    tss: 66,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 5,
    blocks: [
      warmup(15),
      work(4, 0.95, 5),
      rest(3),
      work(4, 0.95, 5),
      rest(3),
      work(4, 0.95, 5),
      rest(3),
      work(4, 0.95, 5),
      rest(3),
      work(4, 0.95, 5),
      cooldown(8),
    ],
  },

  // ── Tier 4 ────────────────────────────────────────────────────────────────
  {
    id: 't4-hiit-6',
    tier: 'T4',
    title: 'HIIT VO2max (6 reps)',
    subtitle: '6×4 @ ~110% FTP',
    durMin: 107,
    tss: 110,
    cadenceLabel: '60–70 rpm',
    expectedClusters: 6,
    blocks: [
      warmup(15),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      rest(4),
      work(5, 1.1, 4),
      cooldown(15),
    ],
  },
  {
    id: 't4-sit-2',
    tier: 'T4',
    title: 'SIT (2 sets)',
    subtitle: '2×(4×30s max)',
    durMin: 76,
    tss: 62,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 2,
    blocks: [
      warmup(15),
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      rest(15),
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      cooldown(15),
    ],
  },
  {
    id: 't4-sit-3',
    tier: 'T4',
    title: 'SIT (3 sets)',
    subtitle: '3×(4×30s max) · 12 × 30s sprints',
    durMin: 109,
    tss: 90,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 3,
    blocks: [
      warmup(15),
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      rest(15),
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      rest(15),
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      sprintRest,
      sprint(),
      cooldown(15),
    ],
  },
  {
    id: 't4-torquemax',
    tier: 'T4',
    title: 'TorqueMax',
    subtitle: '6×2–3 @ 105–110% FTP',
    durMin: 71,
    tss: 73,
    cadenceLabel: '50–60 rpm',
    expectedClusters: 6,
    blocks: [
      warmup(15),
      work(5, 1.08, 2, 30),
      rest(3),
      work(5, 1.08, 2, 30),
      rest(3),
      work(5, 1.08, 2, 30),
      rest(3),
      work(5, 1.08, 2, 30),
      rest(3),
      work(5, 1.08, 2, 30),
      rest(3),
      work(5, 1.08, 2, 30),
      cooldown(15),
    ],
  },
]
